application: hr-note
version: blog-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /index
  script: hello.app

- url: /blog/*
  script: blog.app

- url: /wiki/*
  script: wiki.app

- url: /note/*
  script: note.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
